services:
  mysql:
    image: mysql:8.0
    container_name: url_shortener_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: urlshortener
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - url-shortener-network

  app:
    build: .
    container_name: url_shortener_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: urlshortener
      DB_USER: appuser
      DB_PASSWORD: apppassword
    depends_on:
      - mysql
    networks:
      - url-shortener-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mysql_data:

networks:
  url-shortener-network:
    driver: bridge